version: "3.7"
services:
  postgres:
    build: ./database
    env_file: .env
    ports:
      - "${DB_PORT}:${DB_PORT}"
  migrate:
    build: ./migrate
    volumes:
      - ./migrate/src:/src
    entrypoint: ["./dev.sh"]
    depends_on:
      - postgres
  api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
    command: npm run dev
  ui:
    build: ./ui
    volumes:
      - ./ui:/usr/src/app
    command: npm run dev
