version: "3.7"
services:
  postgres:
    container_name: graph_editor_db
    build: ./database
    ports:
      - "5432:5432"
  api:
    container_name: graph_editor_api
    build: ./api
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
  ui:
    container_name: graph_editor_ui
    build: ./ui
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
      PORT: 3000