version: "3.7"
services:
  # TODO: Set the env-production values correctly (gitlab secrets?)
  postgres:
    env_file: env-production
  api:
    command: npm run start
    env_file: env-production
  ui:
    command: npm run start
    env_file: env-production
