version: "3.7"
services:
  postgresql:
    container_name: graph_editor_db
    build: ./database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD
    env_file: .env
    volumes:
      - ./database/data:/tmp_data
  api:
    container_name: graph_editor_api
    build: ./api
    ports:
      - "4000:4000"
    environment:
      PORT: $API_PORT
    env_file: .env
    volumes:
      - ./api:/usr/src/app
  ui:
    container_name: graph_editor_ui
    build: ./ui
    ports:
      - "3000:3000"
    environment:
      HOST: $UI_HOST
      PORT: $UI_PORT
    volumes:
      - ./ui:/usr/src/app