version: "3.7"
services:
  migrate:
    image: ${CI_REGISTRY_IMAGE-local}/migrate:${CI_COMMIT_SHORT_SHA-latest}
    command: up
    env_file: .env
  api:
    image: ${CI_REGISTRY_IMAGE-local}/api:${CI_COMMIT_SHORT_SHA-latest}
    ports:
      - "4000:4000"
    env_file: .env
    environment:
      PORT: 4000
      UI_PORT: 3000
  ui:
    image: ${CI_REGISTRY_IMAGE-local}/ui:${CI_COMMIT_SHORT_SHA-latest}
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      API_PORT: 4000
