version: "3.7"
services:
  postgresql:
    volumes:
      - ./database/migrations:/tmp_migrations
  seed:
    build: migrate/migrate
    volumes: ./database
  api:
    volumes:
      - ./api:/usr/src/app
  ui:
    volumes:
      - ./ui:/usr/src/app