version: "3.7"
services:
  postgres:
    build: ./database
    expose:
      - 5432
    env_file: env-production
  migrate:
    entrypoint: ["./test.sh"]
    depends_on:
      - postgres  
  api:
    command: npm run test
    volumes:
      - ./api:/usr/src/app
      
