version: "3.7"
services:
  postgresql:
    container_name: graph_editor_db
    build: ./database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  api:
    container_name: graph_editor_api
    build: ./api
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgresql
      PORT: 3000
    volumes:
      - ./api:/usr/src/app
  ui:
    container_name: graph_editor_ui
    build: ./ui
    ports:
      - "4000:4000"
    environment:
      HOST: 0.0.0.0
      PORT: 4000
    volumes:
      - ./ui:/usr/src/app