version: "3.7"
services:
  postgres:
    image: ${CI_REGISTRY_IMAGE-local}/postgres:${CI_COMMIT_SHORT_SHA-latest}
    build: ./database
    env_file: .env
    ports:
      - "${DB_PORT-5432}:${DB_PORT-5432}"
  migrate:
    build: ./migrate
    volumes:
      - ./migrate/src:/src
    entrypoint: ["./dev.sh"]
    depends_on:
      - postgres
  api:
    build:
      context: ./api
      target: dev
    volumes:
      - ./api:/usr/src/app
    command: npm run dev
  ui:
    build:
      context: ./ui
      target: dev
    volumes:
      - ./ui:/usr/src/app
    command: npm run dev
