BEGIN;

DROP FUNCTION ${GRAPH_EDITOR_SCHEMA}.remove_person(text, text);
DROP FUNCTION ${GRAPH_EDITOR_SCHEMA}.register_person(text, text);
DROP FUNCTION ${GRAPH_EDITOR_SCHEMA}.authenticate(text, text);
DROP TYPE ${GRAPH_EDITOR_SCHEMA}.auth_token;
DROP TABLE ${GRAPH_EDITOR_SCHEMA}_private.person_account CASCADE;
DROP TABLE ${GRAPH_EDITOR_SCHEMA}.graph CASCADE;
DROP TABLE ${GRAPH_EDITOR_SCHEMA}.person CASCADE;
DROP FUNCTION trigger_set_timestamp();

REVOKE ALL PRIVILEGES ON schema ${GRAPH_EDITOR_SCHEMA} FROM ${GRAPH_EDITOR_SCHEMA}_anonymous;
REVOKE ALL PRIVILEGES ON schema ${GRAPH_EDITOR_SCHEMA} FROM ${GRAPH_EDITOR_SCHEMA}_person;
REVOKE ALL PRIVILEGES ON schema ${GRAPH_EDITOR_SCHEMA} FROM ${GRAPH_EDITOR_SCHEMA}_postgraphile;

DROP ROLE ${GRAPH_EDITOR_SCHEMA}_anonymous;
DROP ROLE ${GRAPH_EDITOR_SCHEMA}_person;
DROP ROLE ${GRAPH_EDITOR_SCHEMA}_postgraphile;

DROP SCHEMA ${GRAPH_EDITOR_SCHEMA} CASCADE;
DROP SCHEMA ${GRAPH_EDITOR_SCHEMA}_private CASCADE;


COMMIT;